### ISSUE TITLE
1.2.1 does not download the library

### ISSUE THREAD

**Issue by danielwilson1702** [int02h/primaree#11]
Hi it looks like there might be an issue with 1.2.1 or maybe Android Studio is the issue. 1.2.0 is fine but if I try 1.2.1 it's like there's no code there at all so `import com.dpforge.primaree.PrimareeApplication` fails etc.

Anyway great lib thanks!

**Comment by int02h** [comment]
Hello!
Sorry for the long response. Indeed in Maven I don't see 1.2.1. Let me upload it again.

**Comment by int02h** [comment]
@danielwilson1702 now it's [deployed](https://repo1.maven.org/maven2/com/dpforge/primaree/1.2.1/). Please confirm that everything is ok and I will close the issue.

**Comment by int02h** [comment]
I am closing the issue. If you ever meet this problem again please let me know by creating an issue. Thanks!

**Comment by vedraj360** [comment]
Hi, I tried it, but it's still not working.

**Comment by int02h** [comment]
@vedraj360 could share a sample project or at least the dependencies part of the Gradle script?

**Comment by vedraj360** [comment]
Below are the screenshot of my gradle files
![image](https://github.com/int02h/primaree/assets/37593781/1df75626-1880-4a18-9277-d7d6f7f69283)

![image](https://github.com/int02h/primaree/assets/37593781/908ce73a-b4b9-4bdb-b615-775b1746dcfa)

PS: It is working when I am using this ->  implementation 'com.dpforge:primaree:1.2.0'

**Comment by dsvoronin** [comment]
Can confirm: it's not working

1.2.1 doesn't have aar deployed. See:
https://repo.maven.apache.org/maven2/com/dpforge/primaree/1.2.1/
https://repo.maven.apache.org/maven2/com/dpforge/primaree/1.2.0/

**Comment by int02h** [comment]
I've published version [1.2.2](https://repo.maven.apache.org/maven2/com/dpforge/primaree/1.2.2/). Looks like now everything is fine with the .aar file there. The problem with 1.2.1 was because of the inaccurate migration of Maven publish scripts. Sorry for that.
